image: gitpod/workspace-base

tasks:
- name: install all software and download databases
  init: |
    curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
    bash Mambaforge-$(uname)-$(uname -m).sh -b -p /workspace/conda && rm Mambaforge-$(uname)-$(uname -m).sh
    /workspace/conda/bin/mamba init bash
    source ${HOME}/.bashrc
    mamba create -n omacademy -c conda-forge python=3.9 -y
    mamba activate omacademy
    cd /workspace/SIBBiodiversityBioinformatics2024/Module3_FastOMA/working_dir/
    wget https://github.com/DessimozLab/FastOMA/archive/refs/heads/dev.zip
    unzip dev.zip
    mv FastOMA-dev FastOMA
    pip install  ./FastOMA[report]
    cd /workspace/
    mamba install -c bioconda mafft -y 
    mamba install -c bioconda fasttree -y
    mamba install -c bioconda iqtree -y
    mamba install -c bioconda nextflow -y
    mamba install -c conda-forge openjdk -y
    pip install pyham
    cd /workspace/SIBBiodiversityBioinformatics2024/Module4_SpeciesTrees/working_dir/
    git clone https://github.com/DessimozLab/f1000_PhylogeneticTree.git
    echo 'export PATH=$PATH:/workspace/SIBBiodiversityBioinformatics2024/Module4_SpeciesTrees/working_dir/f1000_PhylogeneticTree/' >> ${HOME}/.bashrc
    echo 'mamba activate omacademy' >> ${HOME}/.bashrc
    cd /workspace/
    curl -L -O "https://omabrowser.org/All/Metazoa.h5"
    curl -L -O "https://omabrowser.org/All/Saccharomyceta.h5"
    cp Saccharomyceta.h5 /workspace/SIBBiodiversityBioinformatics2024/Module3_FastOMA/working_dir/in_folder/omamerdb.h5
    mv Saccharomyceta.h5 /workspace/SIBBiodiversityBioinformatics2024/Module2_OMAmer/working_dir/omamer_databases/
    mv Metazoa.h5 /workspace/SIBBiodiversityBioinformatics2024/Module2_OMAmer/working_dir/omamer_databases/

  command: |
    source ${HOME}/.bashrc

vscode:
  extensions:
    - anwar.papyrus-pdf

workspaceLocation: "/workspace"
